[build]
  base    = ""
  publish = "build"
  command = "REACT_APP_STAGE=prod npm run build"

[context.production]
  command = "REACT_APP_STAGE=prod npm run build"

[context.deploy-preview]
  command = "REACT_APP_STAGE=prod npm run build"

[context.branch-deploy]
  command = "REACT_APP_STAGE=prod npm run build"


# Redirect legacy URLs to their equivalents
[[redirects]]
  from    = "/assets/resume/resume.txt"
  to      = "/resume.txt"

[[redirects]]
  from    = "/assets/resume/resume.pdf"
  to      = "/resume.pdf"

[[redirects]]
  from    = "/contact_me/"
  to      = "/"

[[redirects]]
  from    = "/projects/"
  to      = "/"

# The HTML version is the canonical version of the Resume. Alternate assets
# can indicate this to crawlers via the link header.
[[headers]]
  for = "/resume.*"
  [headers.values]
    Link = '/resume/; rel="canonical";'

[[redirects]]
  from = "https://welfley.netlify.com/*"
  to = "https://welfley.me/:splat"
  status = 301
  force = true
