{% extends 'secondary.phtml' %}

{% block title %}{{block.super}}: Projects{% endblock %}
{% block body_attributes %}{{block.super}} id="projects" class="secondary_page"{% endblock %}
{% block meta_description %}This is Thomas Welfley's portfolio. It contains information about several of the projects that Thomas has worked on over the last few years.{% endblock %}

{% block subheading %}Projects{% endblock %}
{% block secondary_page_content %}{% get_latest projects.Project 8 as projects %}
    {% if projects %}
    <nav id="project_nav">
        <p id="prev"><a href="#prev">Previous</a></p>
        <ul id="project_selector">{% for project in projects%}
            <li {% if forloop.first %}class="active"{% endif %} id="link_proj_{{project.name|slugify}}"><a href="#proj_{{project.name|slugify}}">{% if project.icon %}<img src="{{project.icon.url}}" alt="{{project.name}}" />{% else %}{{project.name}}{% endif %}</a></li>{% endfor %}
        </ul>
        <p id="next"><a href="#next">Next</a></p>
    </nav>
    <section id="project_slideshow">
        <ul id="project_data">{% for project in projects %}
            <li id="proj_{{project.name|slugify}}">
                {% include "project.phtml" %}
            </li>{% endfor %}
        </ul>
    </section>
    {% else %}
    <section class="secondary_page_content">
        <p>I haven't posted about any of my projects yet. Check back soon.</p>
    </section>
    {% endif %}
{% endblock %}
