{% extends 'base.phtml' %}

{% block title %}{{block.super}}: Portfolio{% endblock %}
{% block body_attributes %}{{block.super}} id="home"{% endblock %}

{% block content %}
		<section id="why">
			<h1>Here's why:</h1>
			<p><strong>Every website I’ve ever made sucks.</strong> Yep, you read that right. Great web developers are always learning and always improving. If they come to the end of a project and can’t admit that their implementation sucks in some way, then they’re either being dishonest or they’ve stopped paying attention.</p>
			<p>Fortunately, that’s just not how I operate. I make a point to learn from my work and, as a result, <strong>anything I build for you will suck less than everything I’ve built previously</strong>. That’s a promise.</p>
		</section>
		<section id="know">
			<h1>What I know:</h1>
			<section id="frontend">
				<p><strong class="start">Frontend.</strong> I’m really good with <strong>HTML</strong>, <strong>CSS</strong>, and <strong>jQuery</strong>. I can take a comp, slice it six ways to Sunday, and serve the beautiful results on a silver platter of <strong>semantic, well-formed goodness</strong> (without breaking a sweat).</p>
				<p>I’ve hired over 20 developers and trained them extensively in accessibility and frontend development. Some of them even turned out pretty good.</p>
			</section>
			<section id="backend">
				<p><strong class="start">Backend.</strong> A while back, I broke up with <strong>PHP</strong> and fell madly in love with <strong>Python</strong>. I currently maintain an open source API library for Posterous (<a href="http://github.com/thomasw/pyposterous">pyposterous</a>), and I’m the lead developer for a number of applications built with sweet, sweet <strong>Django</strong>&mdash;including <a href="http://hootcourse.com/">HootCourse</a>, <a href="http://presskitn.com/">Presskit’n</a>, and <a href="http://atlibs.matchstrike.net/">@libs</a>.</p>
				<p>I also have some experience wielding <strong>RabbitMQ + Celery</strong> for asynchronous processing. </p>
			</section>
		</section>
{% endblock %}