{% extends 'base.phtml' %}

{% block title %}{{block.super}}{% endblock %}

{% block content %}
		<header>
			<h1>{% block subheading %}Subheading{% endblock %}</h1>
			<nav>
				<ul>{% block subnav %}
					<li class="home"><a href="{% url index %}">Home</a></li>
				{% endblock %}</ul>
			</nav>
		</header>
	
		{% block secondary_page_content %}
		<section class="secondary_page_content">
			<p>Secondary page content.</p>
		</section>
		{% endblock %}
{% endblock %}