Hello!

This is your trustworthy contact form, again. The daily message limit for your
contact form has been reached. I won't send you any more e-mails today, I 
promise. Don't worry though. None of your messages will be lost. You can 
always view them via Django's management console.

Here is the message that broke the contact form's back:

Created: {{message.created}}
E-mail address: {{message.email}}

Message:

{{message.message}}

